name: travel_friend
description: travel_friend flutter.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^1.0.9
  json_annotation: ^2.0.0
  fluttertoast: ^2.1.5
  photo_view: ^0.1.0
  flutter_html_view: ^0.5.10
  shared_preferences: ^0.4.3
  flutter_webview_plugin: ^0.3.0+2

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resource/friends_agreement.html
    - images/icon_weixin.png
    - images/icon_logo.png
    - images/icon_close.png
    - images/icon_chat_nor.png
    - images/icon_chat_selected.png
    - images/icon_mate_nor.png
    - images/icon_mate_selected.png
    - images/icon_mine_nor.png
    - images/icon_mine_selected.png
    - images/default_avatar.png
    - images/icon_female.png
    - images/icon_man.png
    - images/mate_date_bg.png
    - images/icon_location.png
    - images/icon_comment.png
    - images/icon_love.png
    - images/icon_love_selected.png
    - images/icon_repost.png
    - images/default_image.png
    - images/bg_center_cat.png
    - images/icon_arrow_down.png
    - images/icon_arrow_up.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
